name: Lint Scripts

on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "**.md"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.ts"
      - "**.md"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint all packages
        run: pnpm -r run lint
